### Pipeline options

# Input parameters
input_format: "fastq" #fastq or bam (aligned bam)

# Select which parts of the pipeline should be run
steps:
  scarseq: false #analysis of scarseq data
  okseq: false #utilization of OKseqHMM
  cutrun: true #annotation of cut&run with SEACR

# Output parameters
output_dir: "/mnt/beegfs02/scratch/m_coulee/H3K9me3_analysis"

# Path to design file
design: "/home/m_coulee/Post-doc/H3K9me3_pipeline/H3K9me3_design.csv"

# References information
references:
  genome_fasta: "/home/m_coulee/annotation/mm39.fa.gz"
  genome: "mm39"
  index: "/home/m_coulee/annotation/bowtie2_index"
  chr_size: "/home/m_coulee/annotation/mm39.chrom.sizes.txt"
  adapters: "/home/m_coulee/adapters.fa"
  IZ: "/home/m_coulee/E14_OKseq_IZ.bed"
  bins: "/home/m_coulee/mm39_bins.bed"

# Tools parameters
cutadapt_parameters:
  length: 100
  quality: 10

seacr_parameters:
  mode: "stringent" #stringent or relaxed
  normalisation: "non" #norm (used if you have IgG) or non
  igg: "true" #true or false

okseqhmm_parameters:
  threshold: 10
  binSize: 1000 # min 1000
  winS: 15

graph_parameters:
  distance: 50000
