### Pipeline options

# Input parameters
input_format: "fastq" #fastq or bam (aligned bam)

# Select which parts of the pipeline should be run
steps:
  scarseq: true # Analysis of SCAR-seq data
  okseq: false # Analysis of OK-seq data
  cutrun: false # Analysis of CUT&RUN data (utilisation of SEACR)

# Output parameters
output_dir: "/mnt/beegfs01/scratch/<your_name>/<data>_analysis"

# Path to design file
design: "/mnt/beegfs01/scratch/<your_name>/<PIPELINE_design.csv>"

# References information
references:
  genome_fasta: "/home/m_coulee/annotation/mm39.fa.gz"
  genome: "mm39"
  index: "/home/m_coulee/annotation/bowtie2_index"
  chr_size: "/home/m_coulee/annotation/mm39.chrom.sizes.txt"
  adapters: "/home/m_coulee/adapters.fa"
  IZ: "/home/m_coulee/E14_OKseq_IZ.bed" #Necessary only for scarseq step
  bins: "/home/m_coulee/mm39_bins.bed"

# Tools parameters
cutadapt_parameters:
  length: 100
  quality: 10

macs2_parameters:
  model: "" #empty (default: narrow) or --board
  genome: "2.7e+9" #2.7e+9 (mus musculus) or 2.9e+9 (human)

okseqhmm_parameters:
  threshold: 10
  binSize: 1000 # min 1000
  winS: 15

graph_parameters:
  distance: 50000
