### Pipeline options

# Input parameters
input_format: "fastq" #fastq or bam (aligned bam)

# Select which parts of the pipeline should be run
steps:
  scarseq: true #analysis of scarseq data
  okseq: false #utilization of OKseqHMM
  cutrun: false #annotation of cut&run with SEACR

# Output parameters
output_dir: "/mnt/beegfs01/scratch/m_coulee/H3K9me3_analysis"

# Path to design file
design: "/mnt/beegfs01/scratch/m_coulee/H3K9me3_analysis/H3K9me3_design.csv"

# References information
references:
  genome_fasta: "/home/m_coulee/annotation/mm39.fa.gz"
  genome: "mm39"
  index: "/home/m_coulee/annotation/bowtie2_index"
  chr_size: "/home/m_coulee/annotation/mm39.chrom.sizes.txt"
  adapters: "/home/m_coulee/adapters.fa"
  IZ: "/home/m_coulee/E14_OKseq_IZ.bed"
  bins: "/home/m_coulee/annotation/mm39_bins.bed"
  TE: "/home/m_coulee/annotation/mm39_TE.tsv"

# Tools parameters
cutadapt_parameters:
  length: 100
  quality: 10

macs2_parameters:
  model: "" # empty or --broad
  genome: "2.7e+9" #2.7e+9 (mouse) or 2.9e+9 (human)

okseqhmm_parameters:
  threshold: 10
  binSize: 1000 # min 1000
  winS: 15

graph_parameters:
  distance: 50000

TE_parameters:
  OKseq: "/home/m_coulee/E14_OKseq_R1_TE_rfd.tsv"

profile_parameters:
  OKseq: "/home/m_coulee/E14_OKseq_R1_RFD_sm15.tsv"
